// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1, arg2) {
  return window['go']['app']['App']['AddBookmark'](arg1, arg2);
}

export function CreateBookmarkFolder(arg1, arg2) {
  return window['go']['app']['App']['CreateBookmarkFolder'](arg1, arg2);
}

export function DeleteBookmarkFolder(arg1) {
  return window['go']['app']['App']['DeleteBookmarkFolder'](arg1);
}

export function DeleteHost(arg1) {
  return window['go']['app']['App']['DeleteHost'](arg1);
}

export function DeleteMIBModule(arg1) {
  return window['go']['app']['App']['DeleteMIBModule'](arg1);
}

export function ExportMIBTree() {
  return window['go']['app']['App']['ExportMIBTree']();
}

export function FetchTableData(arg1, arg2) {
  return window['go']['app']['App']['FetchTableData'](arg1, arg2);
}

export function GetMIBModuleDetails(arg1) {
  return window['go']['app']['App']['GetMIBModuleDetails'](arg1);
}

export function GetMIBNode(arg1) {
  return window['go']['app']['App']['GetMIBNode'](arg1);
}

export function GetMIBNodeAncestors(arg1) {
  return window['go']['app']['App']['GetMIBNodeAncestors'](arg1);
}

export function GetMIBNodeByName(arg1) {
  return window['go']['app']['App']['GetMIBNodeByName'](arg1);
}

export function GetMIBStats() {
  return window['go']['app']['App']['GetMIBStats']();
}

export function GetMIBTree() {
  return window['go']['app']['App']['GetMIBTree']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ListHosts() {
  return window['go']['app']['App']['ListHosts']();
}

export function ListMIBModules() {
  return window['go']['app']['App']['ListMIBModules']();
}

export function LoadMIBFile() {
  return window['go']['app']['App']['LoadMIBFile']();
}

export function MoveBookmark(arg1, arg2) {
  return window['go']['app']['App']['MoveBookmark'](arg1, arg2);
}

export function MoveBookmarkFolder(arg1, arg2) {
  return window['go']['app']['App']['MoveBookmarkFolder'](arg1, arg2);
}

export function ReloadMIBDatabase() {
  return window['go']['app']['App']['ReloadMIBDatabase']();
}

export function RemoveBookmark(arg1) {
  return window['go']['app']['App']['RemoveBookmark'](arg1);
}

export function RenameBookmarkFolder(arg1, arg2) {
  return window['go']['app']['App']['RenameBookmarkFolder'](arg1, arg2);
}

export function SNMPGet(arg1, arg2) {
  return window['go']['app']['App']['SNMPGet'](arg1, arg2);
}

export function SNMPGetBulk(arg1, arg2, arg3) {
  return window['go']['app']['App']['SNMPGetBulk'](arg1, arg2, arg3);
}

export function SNMPGetNext(arg1, arg2) {
  return window['go']['app']['App']['SNMPGetNext'](arg1, arg2);
}

export function SNMPSet(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SNMPSet'](arg1, arg2, arg3, arg4);
}

export function SNMPWalk(arg1, arg2) {
  return window['go']['app']['App']['SNMPWalk'](arg1, arg2);
}

export function SaveCSVFile(arg1, arg2) {
  return window['go']['app']['App']['SaveCSVFile'](arg1, arg2);
}

export function SaveHost(arg1) {
  return window['go']['app']['App']['SaveHost'](arg1);
}

export function SearchMIBNodes(arg1) {
  return window['go']['app']['App']['SearchMIBNodes'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['App']['Startup'](arg1);
}

export function TouchHost(arg1) {
  return window['go']['app']['App']['TouchHost'](arg1);
}
