// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {snmp} from '../models';
import {mib} from '../models';
import {context} from '../models';

export function AddBookmark(arg1:string,arg2:string):Promise<void>;

export function CreateBookmarkFolder(arg1:string,arg2:string):Promise<app.BookmarkFolderDTO>;

export function DeleteBookmarkFolder(arg1:string):Promise<void>;

export function DeleteHost(arg1:string):Promise<void>;

export function DeleteMIBModule(arg1:string):Promise<void>;

export function ExportMIBTree():Promise<string>;

export function FetchTableData(arg1:snmp.Config,arg2:string):Promise<app.TableDataResponse>;

export function GetMIBModuleDetails(arg1:string):Promise<app.ModuleDetails>;

export function GetMIBNode(arg1:string):Promise<mib.Node>;

export function GetMIBNodeAncestors(arg1:string):Promise<Array<mib.Node>>;

export function GetMIBNodeByName(arg1:string):Promise<mib.Node>;

export function GetMIBStats():Promise<Record<string, number>>;

export function GetMIBTree():Promise<Array<mib.Node>>;

export function Greet(arg1:string):Promise<string>;

export function ListHosts():Promise<Array<mib.HostConfig>>;

export function ListMIBModules():Promise<Array<mib.ModuleSummary>>;

export function LoadMIBFile():Promise<Array<string>>;

export function MoveBookmark(arg1:string,arg2:string):Promise<void>;

export function MoveBookmarkFolder(arg1:string,arg2:string):Promise<void>;

export function ReloadMIBDatabase():Promise<void>;

export function RemoveBookmark(arg1:string):Promise<void>;

export function RenameBookmarkFolder(arg1:string,arg2:string):Promise<void>;

export function SNMPGet(arg1:snmp.Config,arg2:string):Promise<snmp.Result>;

export function SNMPGetBulk(arg1:snmp.Config,arg2:string,arg3:number):Promise<Array<snmp.Result>>;

export function SNMPGetNext(arg1:snmp.Config,arg2:string):Promise<snmp.Result>;

export function SNMPSet(arg1:snmp.Config,arg2:string,arg3:string,arg4:any):Promise<snmp.Result>;

export function SNMPWalk(arg1:snmp.Config,arg2:string):Promise<Array<snmp.Result>>;

export function SaveCSVFile(arg1:string,arg2:string):Promise<boolean>;

export function SaveHost(arg1:mib.HostConfig):Promise<mib.HostConfig>;

export function SearchMIBNodes(arg1:string):Promise<Array<mib.Node>>;

export function Startup(arg1:context.Context):Promise<void>;

export function TouchHost(arg1:string):Promise<void>;
