// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function Emit(arg1:services.Livello,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartDemoLogs():Promise<void>;

export function StopDemoLogs():Promise<void>;
