// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Emit(arg1, arg2) {
  return window['go']['services']['Logger']['Emit'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['services']['Logger']['SetContext'](arg1);
}

export function StartDemoLogs() {
  return window['go']['services']['Logger']['StartDemoLogs']();
}

export function StopDemoLogs() {
  return window['go']['services']['Logger']['StopDemoLogs']();
}
